--Partycje obliczeniowe
---% udzial rodzaju imprezy w danym kraju w odniesieniu do ogolnej kwoty dla calego kraju
SELECT DISTINCT  H_ADRES.KRAJ AS "Kraj", H_RODZAJ_IMPREZY.NAZWA AS "Rodzaj imprezy",
SUM(H_IMPREZA.CENA_BILETU*H_IMPREZA.ilosc) OVER (PARTITION BY H_ADRES.KRAJ,H_RODZAJ_IMPREZY.NAZWA) AS "Kwota dla rodzaju imprezy",
SUM(H_IMPREZA.CENA_BILETU*H_IMPREZA.ilosc) OVER (PARTITION BY H_ADRES.KRAJ) AS "Ogolna kwota dla kraju",
ROUND(100*(SUM(H_IMPREZA.CENA_BILETU*H_IMPREZA.ilosc)OVER (PARTITION BY H_ADRES.KRAJ,H_RODZAJ_IMPREZY.NAZWA))/
(SUM(H_IMPREZA.CENA_BILETU*H_IMPREZA.ilosc)OVER (PARTITION BY H_ADRES.KRAJ)),5) "UDZIAL %" FROM H_IMPREZA JOIN H_ADRES ON H_IMPREZA.ID_ADRES = H_ADRES.ID_ADRES
JOIN H_RODZAJ_IMPREZY ON H_IMPREZA.ID_RODZAJ_IMPREZY = H_RODZAJ_IMPREZY.ID_RODZAJ_IMPREZY
ORDER BY H_RODZAJ_IMPREZY.NAZWA, H_ADRES.KRAJ;

---% udzial krajow w zyskach ogolnych
SELECT DISTINCT  H_ADRES.KRAJ AS "Kraj",
SUM(H_IMPREZA.CENA_BILETU*H_IMPREZA.ilosc) OVER (PARTITION BY H_ADRES.KRAJ) AS "Kwota dla kraju",
SUM(H_IMPREZA.CENA_BILETU*H_IMPREZA.ilosc) OVER (PARTITION BY NULL) AS "Ogolna kwota",
ROUND(100*(SUM(H_IMPREZA.CENA_BILETU*H_IMPREZA.ilosc)OVER (PARTITION BY H_ADRES.KRAJ))/
(SUM(H_IMPREZA.CENA_BILETU*H_IMPREZA.ilosc)OVER (PARTITION BY NULL)),5) "UDZIAL %" FROM H_IMPREZA JOIN H_ADRES ON H_IMPREZA.ID_ADRES = H_ADRES.ID_ADRES
ORDER BY H_ADRES.KRAJ;

---% biletow kazdego rodzaju w ogolnej sumie biletow 
SELECT DISTINCT H_Rodzaj_Imprezy.Nazwa AS "Rodzaj", H_Rodzaj_Biletu.Nazwa AS "Rodzaj biletu", SUM(H_IMPREZA.ilosc) OVER (PARTITION BY H_Rodzaj_Biletu.Nazwa) AS "Ilosc biletow danego rodzjau",
sum(H_IMPREZA.ilosc) OVER (PARTITION BY NULL) "Ilosc biletow ogolna",
ROUND(100*SUM(H_IMPREZA.ilosc) OVER (PARTITION BY H_Rodzaj_Biletu.Nazwa)/
(SUM(H_IMPREZA.ilosc) OVER (PARTITION BY NULL)),2) "UDZIAL %"
FROM H_Impreza JOIN H_Rodzaj_Imprezy ON H_Impreza.id_rodzaj_imprezy = H_Rodzaj_Imprezy.id_rodzaj_imprezy
JOIN H_Rodzaj_biletu ON H_Rodzaj_biletu.id_rodzaj_biletu = H_IMPREZA.id_rodzaj_biletu 
ORDER BY H_Rodzaj_Imprezy.Nazwa,H_Rodzaj_Biletu.Nazwa;

---% udzial danego rodzaju biletu do ogolnej ilosci biletow w kraju
SELECT DISTINCT H_ADRES.KRAJ AS "Kraj", H_Rodzaj_Biletu.Nazwa AS "Rodzaj biletu", SUM(H_IMPREZA.ilosc) OVER (PARTITION BY H_ADRES.KRAJ,H_Rodzaj_Biletu.Nazwa) AS "ILOSC",
sum(H_IMPREZA.ilosc) OVER (PARTITION BY H_ADRES.KRAJ) Ilosc_biletow,
ROUND(100*SUM(H_IMPREZA.ilosc) OVER (PARTITION BY H_ADRES.KRAJ,H_Rodzaj_Biletu.Nazwa)/
(SUM(H_IMPREZA.ilosc) OVER (PARTITION BY H_ADRES.KRAJ)),5) "UDZIAL %"
FROM H_Impreza
JOIN H_Rodzaj_biletu ON H_Rodzaj_biletu.id_rodzaj_biletu = H_IMPREZA.id_rodzaj_biletu
JOIN H_ADRES ON H_IMPREZA.ID_ADRES = H_ADRES.ID_ADRES
ORDER BY H_ADRES.KRAJ, H_Rodzaj_Biletu.Nazwa;


---% udzial kazdego tytulu spektaklu w ogolnych zyskach z danego rodzaju imprezy
SELECT DISTINCT H_RODZAJ_IMPREZY.NAZWA AS "Rodzaj imprezy", H_SPEKTAKL.TYTUL AS "Tytul", SUM(H_IMPREZA.CENA_BILETU*H_IMPREZA.ilosc) OVER (PARTITION BY H_SPEKTAKL.TYTUL) AS "Kwota",
SUM(H_IMPREZA.CENA_BILETU*H_IMPREZA.ilosc) OVER (PARTITION BY H_RODZAJ_IMPREZY.NAZWA) SUMA_KWOTA,
ROUND(100*(SUM(H_IMPREZA.CENA_BILETU*H_IMPREZA.ilosc)OVER (PARTITION BY H_SPEKTAKL.TYTUL))/
(SUM(H_IMPREZA.CENA_BILETU*H_IMPREZA.ilosc) OVER (PARTITION BY H_RODZAJ_IMPREZY.NAZWA)),5) "UDZIAL %"
FROM H_IMPREZA JOIN H_SPEKTAKL ON H_IMPREZA.ID_SPEKTAKL = H_SPEKTAKL.ID_SPEKTAKL
JOIN H_RODZAJ_IMPREZY ON H_IMPREZA.ID_RODZAJ_IMPREZY = H_RODZAJ_IMPREZY.ID_RODZAJ_IMPREZY
ORDER BY H_RODZAJ_IMPREZY.NAZWA, H_SPEKTAKL.TYTUL;