import java.util.ArrayList;
import java.util.List;

public class HandwrittenTypes {
//    public static String[] Rodzaje_Transportu =
//    {
//        "Samolot",
//        "Pociąg",
//        "Autokar",
//        "Tramwaj",
//        "Statek",
//        "Samochód"
//    };

    public enum ETransportType {
        Samolot,
        Pociag,
        Autokar,
        Tramwaj,
        Statek,
        Samochod
    }

    public static String[] Rodzaje_Imprezy = {
            "Film kinowy",
            "Przedstawienie teatralne",
            "Koncert muzyczny",
            "Lot pasazerski",
            "Komunikacja miejska",
            "Wycieczka turystyczna",
            "Rejs morski",
            "Przejazd koleja"
    };

    public static String[] Samochody =
    {
        "Land Rover Range Rover Sport",
            "Vauxhall Corsa",
            "Honda Civic",
            "Audi RS4",
            "VW Passat",
                "Ford K+",
                "Skoda Citigo",
                "Kia Stonic",
                "Subaru Outback",
                "Honda Pilot",
                "BMW X5",
                "Hyundai Elantra",
                "VW Golf",
                "Land Rover Discovery",
                "BMW 7 Series",
                "Ford Mustang",
                "BMW X1",
                "Audi Q5",
                "Volvo V40",
                "Porsche Panamera",
                "Skoda Fabia",
                "Mazda CX-3",
                "Hyundai i30",
                "VW up!",
                "Audi A7",
                "Jaguar E-Pace",
                "Ford Ka",
                "Ford Kuga",
                "Kia Sorento",
                "Renault Zoe",
                "Smart Fortwo",
                "Jeep Wrangler",
                "Hyundai Sonata",
                "Cadillac ATS",
                "Volkswagen Passat",
                "Dodge Caravan",
                "Ford Fiesta",
                "Buick Enclave",
                "Mercedes-Benz GLA-Class",
                "Nissan GT-R",
                "Honda CR-V",
                "Ford C-MAX",
                "Kia Sorento",
                "Skoda Yeti",
                "Skoda Felicia",
                "Mercedes-Benz E-Class",
                "Lexus ES",
                "Mazda CX-9",
                "Volvo XC40",
                "Citroen C4",
    };

    public static String[] Statki =
            {
                    "The Vulcan",
                    "Nepean",
                    "The Pegwell Bay",
                    "Moselle",
                    "Prosperous",
                    "The Blackmore Lady",
                    "Burton",
                    "Monsieur",
                    "Havick",
                    "The Eastway",
                    "The Caledonia",
                    "Himalaya",
                    "Dundee",
                    "Sentinel",
                    "The Snowdrop",
                    "Artifex",
                    "The Earl of Peterborough",
                    "Elias",
                    "Juno",
                    "Tonbridge Castle",
                    "Express",
                    "Talbot",
                    "Greyhond",
                    "Mortar",
                    "Ajdaha",
                    "Wakeful",
                    "Blackmorevale",
                    "The Esther",
                    "The Meleager",
                    "Skirmisher",
                    "Bilsthorpe",
                    "The Jaguar",
                    "Imogen",
                    "The Polsham",
                    "Godetia",
                    "Aster",
                    "The Arawa",
                    "Gulland",
                    "The Minstrel",
                    "Shalimar",
                    "Dartington",
                    "Burford",
                    "The Vetch",
                    "Cordelia",
                    "Assistance",
                    "The Felixstowe",
                    "Fordham",
                    "The Tristram",
                    "Badger",
                    "Pigmy"
            };
    public static String[] Pociągi = {
            "THE ITALO AND FRECCIAROSSA",
            "RENFE AVE",
            "VENICE SIMPLON ORIENT EXPRESS",
            "GOLDEN EAGLE",
            "BLUE TRAIN",
            "THE GHAN",
            "ROVOS TRAIL",
            "THE ROCKY MOUNTAINEER",
            "HOKKAIDO RAILWAY TRAIN",
            "SHANGHAI MAGLEV",
            "Nightingale Tracks",
            "Somerset Line",
            "Grand Meadows Tracks",
            "Fogland Line",
            "Sapphire Coast Tracks",
            "Tadpole River Route",
            "Murky Marsh Line",
            "Soundscape Loop Line",
            "Surfer Coast Line",
            "Coal Belt Rail Line",
            "New North Train Line",
            "Glacier Forest Line",
            "Wetlands Speed Line",
            "Frozen Pinnacle Line",
            "Hollow Rock Line",
            "Old Forest Tracks",
            "Savannah Line",
            "Maiden Stone Tracks",
            "Silverstone Tracks",
            "Serenity Tracks",
            "Fozen Tundra Main Line",
            "Uncanny Valley Tracks",
            "Boulderland Line",
            "Greenbelt Train Line",
            "Shark Harbor Tracks",
            "High Valley Tracks",
            "Ironbark Line",
            "Flower Gardens Route",
            "Sunny Fields Tracks",
            "Grand Continental Line",
            "University Tracks",
            "Savage Coast Tracks",
            "Songbird Tracks",
            "Lowland Route",
            "North Central Route",
            "High Mountain Route",
            "Eastern Route",
            "Riverfront Route",
            "Wild Ocean Train Line",
            "Tadpole River Rail Line"
    };

    public static String[] Samoloty = {
            "ATR 42",
            "ATR 72",
            "Airbus A220",
            "Airbus A300",
            "Airbus A310",
            "Airbus A318",
            "Airbus A319",
            "Airbus A320",
            "Airbus A321",
            "Airbus A330",
            "Airbus A340",
            "Airbus A350",
            "Airbus A380",
            "Antonov An-140",
            "Antonov An-148",
            "Antonov An-158",
            "Beechcraft 200 Super King Air",
            "Beechcraft 1300",
            "Beriev Be-200",
            "British Aerospace BAe 146",
            "Boeing 717",
            "Boeing 757",
            "Boeing 767",
            "Boeing 777",
            "Boeing 787",
            "Bombardier CRJ-100",
            "Bombardier CRJ-200",
            "Bombardier CRJ-700",
            "Bombardier CRJ-900",
            "Bombardier Dash 8",
            "CASA C-212 Aviocar",
            "Cessna 208",
            "Cessna 404",
            "Comac C919 (project)",
            "Convair CV5800",
            "de Havilland Canada Dash 7",
            "De Havilland Canada Dash 8",
            "Dornier 328",
            "Embraer EMB 121 Xingu",
            "Embraer EMB 120 Brasilia",
            "Embraer EMB 820C",
            "Embraer/FMA CBA 123 Vector",
            "Fokker 50",
            "Fokker 70",
            "Fokker 100",
            "Irkut MS-21 (project)",
            "Ilyushin Il-86",
            "Ilyushin Il-96",
            "Ilyushin Il-114",
            "Indonesian Aerospace N-219"
    };

    public static String[] Autokary = {
            "Wrightbus Pulsar Gemini",
            "MERCEDES TOURISMO 2013",
            "Wrightbus Pulsar Gemini HEV",
            "MERCEDES TRAVEGO VIP CLASS",
            "NEOPLAN N 1216 HD",
            "BOVA FUTURA 2009",
            "Nissan Space Runner RA",
            "BOVA FUTURA 2007",
            "Nissan Space Runner RP",
            "MAN R07",
            "MERCEDES O818 TEAMSTAR 2005",
            "MERCEDES O818 TEAMSTAR 2004",
            "Iveco Urbanway 18m",
            "MERCEDES O818 TEAMSTAR 2006",
            "Solaris Valletta",
            "Nissan UA",
            "MERCEDES O818 TEAMSTAR 2002",
            "MERCEDES SPRINTER 519 2015",
            "MERCEDES SPRINTER 519 2013",
            "Isuzu Turquoise",
            "MERCEDES VITO TOURER VIP CLASS",
            "MERCEDES VITO VIP",
            "VW T6 CARAVELLE",
            "VW CARAVELLE VIP",
            "EPV EcoSmart",
            "BYD K9",
            "Eurabus 2.0",
            "Volvo 7700",
            "Volvo 7900",
            "Volvo 8700",
            "Volvo 8900",
            "Volvo 9700",
            "Volvo 9900",
            "Solaris Alpino",
            "Autosan Eurolider 12",
            "Autosan H9",
            "Autosan H10",
            "Solaris Interlink",
            "Neoplan K4010TD",
            "Neoplan K4016TD",
            "Jelcz L11",
            "Jelcz M11",
            "Jelcz M125M",
            "Neoplan N4009",
            "Jelcz PR110D",
            "Volvo Super Olympian",
            "Solaris Trolilno",
            "Solaris Urbino 9",
            "Solaris Urbino 10",
            "Solaris Vacanza 12"
    };

    public static String[] Tramwaje = {
            "A class Melbourne tram",
            "ADtranz low floor tram",
            "B-class Melbourne tram",
            "AKSM",
            "ATM Class 1500",
    "ATM Class 4600 and 4700",
    "Avanto",
            "Birney",
    "CarGoTram",
    "C-class Melbourne tram",
            "CAF Urbos",
            "California car",
            "Citytram",
            "Combino",
            "Crotram",
            "D-class Melbourne tram",
            "Dick Kerr Type Tram",
            "E-class Melbourne tram",
            "F-class Melbourne tram",
            "DL",
            "Double-decker tram",
    "Socimi Eurotram",
    "Bombardier Flexity",
    "Gothawagen",
    "Gelede Tram Lang [nl]",
    "H type Adelaide tram",
    "Bombardier Incentro",
    "K-1 (tram) [uk]",
    "Konstal",
            "PESA",
    "PCC streetcar",
    "Toronto PCC",
    "Sirio",
    "Bursa",
    "Turkey",
    "SL95",
    "Soviet/Latvian RVR",
    "LM/LVS",
    "MTV,",
    "КТМ [ru]",
    "Spektr [ru]",
    "Škoda ForCity",
    "AnsaldoBreda T-68",
    "AnsaldoBreda T-69",
    "Tatra T3",
    "Tatra KT4",
    "TMK 2200",
    "Tramino",
    "Tramway Français Standard",
    "TW 6000",
    "Ultra Low Floor",
    "US Standard Light Rail Vehicle",
            "Variotram",
    "Z-class Melbourne tram"
    };

    public static String[] Rodzaje_biletów = {
            "Bilet ulgowy",
            "Bilet weekendowy",
            "Bilet grupowy",
            "Bilet normalny",

                    "Bilet przewozowy normalny",
                    "Bilet przewozowy ulgowy",
                    "Bilet przewozowy grupowy",

                    "Bilet rejsowy normalny",
                    "Bilet rejsowy ulgowy",
                    "Bilet rejsowy grupowy",

                    "Bilet tramwajowy normalny dobowy",
                    "Bilet tramwajowy ulgowy dobowy",
                    "Bilet tramwajowy normalny 3 dniowy",
                    "Bilet tramwajowy ulgowy 3 dniowy",
                    "Bilet tramwajowy normalny weekendowy",
                    "Bilet tramwajowy ulgowy weekendowy",
                    "Bilet tramwajowy normalny jednorazowy",
                    "Bilet tramwajowy ulgowy jednorazowy",
                    "Bilet tramwajowy okresowy",
                    "Bilet tramwajowy grupowy",

                    "Bilet autokarowy grupowy",
                    "Bilet autokarowy normalny",
                    "Bilet autokarowy ulgowy",
                    "Bilet autokarowy okresowy",

                    "Bilet lotniczy grupowy",
                    "Bilet lotniczy normalny",
                    "Bilet lotniczy ulgowy",

                    "Bilet kolejowy normalny",
                    "Bilet kolejowy ulgowy",
                    "Bilet kolejowy grupowy",
                    "Bilet kolejowy okresowy"
    };

}
